### PR TITLE
updated goreleaser.yml and added github action workflow

### PR DESCRIPTION
**Pull request by BRO3886**
* continued from PR #48
* added support for arm64 build
* added github actions worflow (set `GH_TOKEN` as repo secret)
* added workflow for using github actions, works only on a tag:

1. Push to branch
2. Create tag (`git tag create -a vX.X.X -m "info about tag"`)
3. git push origin {tag}

    This will run the action

### CODE REVIEW

**Comment by athul** [comment]
Hey @BRO3886 sorry for the late response. Did you try a local dry run on this?

**Comment by BRO3886** [comment]
yes I tried local run, [ran the action on my fork too](https://github.com/BRO3886/hopp-cli/runs/4906459070?check_suite_focus=true), it passed till the releasing part which failed because it was trying to release under hoppscotch/hopp-cli

Implemented the same for a personal project, which worked fine. You can check the run [here](https://github.com/BRO3886/gtasks/runs/4906721021?check_suite_focus=true)

**Comment by BRO3886** [comment]
@athul

**Review by athul — APPROVED** [review]

**Comment by athul** [comment]
Awesome, I'll merge this. Since I don't have repository rights here, @liyasthomas it would be great if you could add a GitHub Token to this repo secrets by the name `GH_TOKEN`? If that's done, we're good to release a new tag 😄

**Comment by liyasthomas** [comment]
@athul done 👍 
I've added the token.

**Comment by athul** [comment]
@BRO3886 

```
2022-02-01T16:50:36.3041773Z [34m[1m      •[0m running hook             [0m [34mhook[0m=make pack-releases
2022-02-01T16:50:40.6179013Z [34m[1m      •[0m running hook             [0m [34mhook[0m=make pack-releases
2022-02-01T16:50:40.6609806Z [31m[1m   ⨯[0m [1mrelease failed after 110.38s[0m[0m [31merror[0m=post hook failed: "stuffbin -a stuff -in dist/hopp-cli_darwin_amd64/hopp-cli -out ./dist/hopp-cli_darwin_amd64/hopp-cli ./templates/index.html ./templates/template.md:/template.md; stuffbin -a stuff -in dist/hopp-cli_darwin_arm64/hopp-cli -out ./dist/hopp-cli_darwin_arm64/hopp-cli ./templates/index.html ./templates/template.md:/template.md; stuffbin -a stuff -in dist/hopp-cli_linux_386/hopp-cli -out ./dist/hopp-cli_linux_386/hopp-cli ./templates/index.html ./templates/template.md:/template.md; stuffbin -a stuff -in dist/hopp-cli_linux_amd64/hopp-cli -out ./dist/hopp-cli_linux_amd64/hopp-cli ./templates/index.html ./templates/template.md:/template.md; stuffbin -a stuff -in dist/hopp-cli_windows_386/hopp-cli.exe -out ./dist/hopp-cli_windows_386/hopp-cli.exe ./templates/index.html ./templates/template.md:/template.md; stuffbin -a stuff -in dist/hopp-cli_windows_amd64/hopp-cli.exe -out ./dist/hopp-cli_windows_amd64/hopp-cli.exe ./templates/index.html ./templates/template.md:/template.md;\nstuffing failed: open dist/hopp-cli_darwin_amd64/hopp-cli: no such file or directory\nstuffing failed: open dist/hopp-cli_darwin_arm64/hopp-cli: no such file or directory\nstuffing failed: open dist/hopp-cli_linux_386/hopp-cli: no such file or directory\nstuffing failed: open dist/hopp-cli_linux_amd64/hopp-cli: no such file or directory\nstuffing failed: open dist/hopp-cli_windows_386/hopp-cli.exe: no such file or directory\nstuffing failed: open dist/hopp-cli_windows_amd64/hopp-cli.exe: no such file or directory\nmake: *** [Makefile:41: pack-releases] Error 1\n": exit status 2
2022-02-01T16:50:40.6659957Z ##[error]The process '/opt/hostedtoolcache/goreleaser-action/1.4.1/x64/goreleaser' failed with exit code 1
2022-02-01T16:50:40.6749912Z Post job cleanup.
2022-02-01T16:50:40.8171854Z [command]/usr/bin/git version
2022-02-01T16:50:40.8232182Z git version 2.34.1
2022-02-01T16:50:40.8278803Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-02-01T16:50:40.8340734Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-02-01T16:50:40.8632256Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-02-01T16:50:40.8696909Z http.https://github.com/.extraheader
2022-02-01T16:50:40.8705755Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-02-01T16:50:40.8751304Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-02-01T16:50:40.9270588Z Cleaning up orphan processes
```

Seems like there are some errors here

**Comment by athul** [comment]
Lemme try to fix this

**Comment by BRO3886** [comment]
Hi, checking..
I added a relative path on [Makefile L41](https://github.com/hoppscotch/hopp-cli/blob/ff66e0d2c916f492268bdbedd02b19c36885f704/Makefile#L41), after that the "no such file or directory" issue resolved for me

**Comment by BRO3886** [comment]
@athul, please remove the ./ (relative path), it should work after that. My bad...

**Comment by BRO3886** [comment]
I think the issue is intermittent, because stuffbin tries to find the files before all files have been built, trying to debug.

**Pull request merged**
